application/carrito/__init__.py
from flask import Blueprint

carrito = Blueprint('carrito', __name__, template_folder='templates')   

from . import routes

application/carrito/routes.py
from datetime import datetime
from flask import redirect, render_template, request, session, url_for, current_app
from flask_login import login_required
from flask_wtf.csrf import CSRFProtect
from application import db
from . import carrito
from flask_login import current_user

csrf = CSRFProtect()

fecha_actual = datetime.now()


@carrito.route("/cart")
def cart():
    """Función para mostrar los productos que tiene en el carrito de compras"""
    data = {
        "titulo": " Carrito de compras",
    }
    return render_template("carrito/cart.html", data=data)


@carrito.route("/cart", methods=["POST"])
@login_required
@csrf.exempt
def add_product_to_cart():
    """
    Funcion para agregar productos al carrito
    """
    _quantity = int(request.form["quantity"])
    _code = request.form["code"]
    # Validar los valores recibidos
    try:
        if _quantity and _code and request.method == "POST":
            with db.connection.cursor() as cur:
                cur.execute("SELECT * FROM producto WHERE code = %s", (_code,))
                row = cur.fetchone()
                if row:
                    row = {desc[0]: value for desc, value in zip(cur.description, row)}
                    itemArray = {
                        row["code"]: {
                            "name": row["name"],
                            "code": row["code"],
                            "description": row["description"],
                            "quantity": float(_quantity),
                            "price": float(row["price"]),
                            "image": row["image"],
                            "total_price": float(_quantity) * float(row["price"]),
                        }
                    }

                    all_total_price = 0
                    all_total_quantity = 0

                    session.modified = True
                    if "cart_item" in session:
                        if row["code"] in session["cart_item"]:
                            for key, value in session["cart_item"].items():
                                if row["code"] == key:
                                    old_quantity = session["cart_item"][key]["quantity"]
                                    total_quantity = old_quantity + _quantity
                                    session["cart_item"][key][
                                        "quantity"
                                    ] = total_quantity
                                    session["cart_item"][key]["total_price"] = (
                                        total_quantity * row["price"]
                                    )
                        else:
                            session["cart_item"].update(itemArray)
                    else:
                        session["cart_item"] = itemArray

                    for key, value in session["cart_item"].items():
                        individual_quantity = int(value["quantity"])
                        individual_price = float(value["total_price"])
                        all_total_quantity += individual_quantity
                        all_total_price += individual_price
                else:
                    return "Producto no encontrado en la base de datos"

                session["all_total_quantity"] = all_total_quantity
                session["all_total_price"] = all_total_price
                next_page = request.form.get("next")
                if next_page is None:
                    next_page = url_for("carrito.cart")
                return redirect(next_page)
                # return redirect(url_for('bienvenida.index'))
        else:
            return "Error al agregar productos al carrito"
    except ImportError as ex:
        current_app.logger.error(
            f"{fecha_actual} Error al agregar productos al carrito {ex}"
        )


@carrito.route("/empty_cart")
def empty_cart():
    """Funcion para quitar los productos del carrito"""
    try:
        session.pop("cart_item", None)
        session.pop("all_total_quantity", None)
        session.pop("all_total_price", None)
        return redirect(url_for("carrito.cart"))
    except Exception as e:
        current_app.logger.error(f"{fecha_actual} Error al vaciar el carrito {e}")


@carrito.route("/delete/<string:code>")
def delete_product(code):
    """Funcio para eliminar productos especificos del carrito"""
    try:
        all_total_price = 0
        all_total_quantity = 0
        session.modified = True

        for item in session["cart_item"].items():
            if item[0] == code:
                session["cart_item"].pop(item[0], None)
                if "cart_item" in session:
                    for key, value in session["cart_item"].items():
                        individual_quantity = int(session["cart_item"][key]["quantity"])
                        individual_price = float(
                            session["cart_item"][key]["total_price"]
                        )
                        all_total_quantity = all_total_quantity + individual_quantity
                        all_total_price = all_total_price + individual_price
                break

        if all_total_quantity == 0:
            session.pop("cart_item", None)
            session.pop("all_total_quantity", None)
            session.pop("all_total_price", None)
        else:
            session["all_total_quantity"] = all_total_quantity
            session["all_total_price"] = all_total_price
        return redirect(url_for("carrito.cart"))
    except ImportError as e:
        current_app.logger.error(
            f"{fecha_actual} Error al eliminar productos al carrito {e}"
        )


@carrito.route("/update_quantity/<string:code>", methods=["POST"])
@login_required
@csrf.exempt
def update_quantity(code):
    try:
        new_quantity = float(request.form["new_quantity"])

        if "cart_item" in session and code in session["cart_item"]:
            # Convert the price to a float before performing the operation
            price = float(session["cart_item"][code]["price"])

            session["cart_item"][code]["quantity"] = new_quantity
            session["cart_item"][code]["total_price"] = new_quantity * float(price)

            # Update the overall total
            all_total_quantity = sum(
                float(item["quantity"]) for item in session["cart_item"].values()
            )
            all_total_price = sum(
                item["total_price"] for item in session["cart_item"].values()
            )

            session["all_total_quantity"] = all_total_quantity
            session["all_total_price"] = all_total_price

            return redirect(url_for("carrito.cart"))
    except Exception as e:
        current_app.logger.error(
            f"{fecha_actual} Error al actualizar la cantidad del producto {code}: {e}"
        )
        return redirect(url_for("carrito.cart"))


@carrito.route("/checkout", methods=["GET", "POST"])
@login_required
@csrf.exempt
def checkout():
    cart_items = session.get("cart_item", {})
    total_quantity = session.get("all_total_quantity", 0)
    total_price = session.get("all_total_price", 0)

    if request.method == "POST":
        # Perform the checkout process here (e.g., update database, create order, etc.)
        # After successful checkout, clear the cart
        session.pop("cart_item", None)
        session.pop("all_total_quantity", None)
        session.pop("all_total_price", None)
        return redirect(url_for("carrito.cart"))
    
    # If it's a GET request, render the checkout page
    data = {
        "titulo": "Verificar Compra",
        "cart_items": cart_items,
        "total_quantity": total_quantity,
        "total_price": total_price,
    }
    return render_template("carrito/checkout.html", data=data)

application/carrito/templates/carrito/cart.html
{% extends './base_template.html' %}

{%block title%}
{{data.titulo}}
{%endblock%}

{% block body %}

{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

<div class="container mt-4">
    <div class="row">
        <div class="col-sm-12">
            <div>
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <ul class="flashes">
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% endwith %}
            </div>
            {% if 'cart_item' in session %}
            <h1 class="text-center  letraExtraGrande">Productos en tu carrito</h1>
            <p><a id="btnEmpty" href="{{ url_for('carrito.empty_cart') }}" class="btn btn-danger">Vaciar Carrito 😢</a>
            </p>

            <div class="table-responsive mt-4">
                <table class="table table-hover table-striped letraPeque">
                    <thead>
                        <tr>
                            <th class=" text-center letraPeque" style="color:#129e31">Productos</th>
                            <th class="text-center letraPeque" style="color:#129e31">Cantidades</th>
                            <th class="text-center letraPeque" style="color:#129e31">Valor Unidad</th>
                            <th class="text-center letraPeque" style="color:#129e31">Precio</th>
                            <th class="text-center letraPeque" style="color:#129e31">Opción</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for key, val in session['cart_item'].items() %}
                        {% set quantity = session['cart_item'][key]['quantity'] %}
                        {% set price = session['cart_item'][key]['price']|float %}
                        {% set item_price = session['cart_item'][key]['total_price']|float %}
                        <tr>
                            <td class="col-sm-7 col-md-7">
                                <div class="media">
                                    <a class="thumbnail pull-left" href="#"> <img class="media-object"
                                            src="/static/imagenes_productos/{{ session['cart_item'][key]['image'] }}"
                                            style="width: 72px; height: 72px;"> </a>
                                    &nbsp;
                                    <div class="media-body" style="padding-left:10px;">
                                        <h4 class="media-heading letraGrisMediana"> &nbsp;&nbsp;{{
                                            session['cart_item'][key]['name']}}</h4>
                                        <!-- <h5 class="media-heading"> by Brand name</h5> -->
                                        <!-- <span>Status: </span><span class="text-success"><strong>In Stock</strong></span> -->
                                    </div>
                                </div>
                            </td>
                            <td class="col-sm-2 col-md-2 media-body text-center" style="padding-left: 10px;">
                                <form class="form-inline" method="POST" action="{{ url_for('carrito.update_quantity', code=session['cart_item'][key]['code']) }}">
                                  <div class="input-group">
                                    <input class="form-control form-control-sm" type="number" name="new_quantity" value="{{ quantity|int  }}" min="1"required>
                                    <div class="input-group-append">
                                      <button type="submit" class="btn botonCuatro btn-sm">Actualizar</button>
                                    </div>
                                  </div>
                                </form>
                            </td>                           
                            
                            <td class="col-sm-1 col-md-1 text-center letraGrisMediana"><strong>${{
                                    "{:,.2f}".format(price) }} </strong></td>
                            <td class="col-sm-1 col-md-1 text-center letraGrisMediana"><strong>${{
                                    "{:,.2f}".format(item_price) }}</strong></td>
                            <td class="col-sm-1 col-md-1">
                                <a href="{{ url_for('carrito.delete_product', code=session['cart_item'][key]['code']) }}"
                                    class="btn btn-danger">
                                    <span class="glyphicon glyphicon-remove"></span> Eliminar
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="4">
                                <h5 class="letraPeque">Cantidad Total:</h5>
                            </td>
                            <td class="text-right">
                                <h5><strong class="letraPeque">{{ "{:,.0f}".format(session['all_total_quantity']) }}</strong></h5>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <h3 class="letraNormalVerde">Total</h3>
                            </td>
                            <td colspan="2" class="text-right">
                                <h3><strong class="letraNormalVerde">$ {{ "{:,.2f}".format(session['all_total_price']) }}</strong></h3>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class=" text-center p-4 ">
                <a href="{{ url_for('bienvenida.index') }}" class="btn botonTres">
                    <span class="fas fa-shopping-cart"></span> Continuar Comprando
                </a>
                <a href="{{ url_for('carrito.checkout') }}" class="btn botonCuatro"><i class="fas fa-dollar-sign"></i> &nbsp;Finalizar compra</a>
            </div>
            {% else: %}
            <div class="container text-center align-items-center mt-4">
                <label class="letraGrande">
                    Tu Carrito esta vacio
                </label>
                <br>
                <div class=" text-center mt-2">
                    <img src="{{ url_for('static', filename='img/carrito.jfif') }}" alt="Mi Imagen" class="img-error">
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>



{% endblock %}

application/carrito/templates/carrito/checkout.html
{% extends './base_template.html' %}

{% block title %}
    {{ data.titulo }}
{% endblock %}

{% block body %}
    {% block head %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://js.stripe.com/v3/"></script>

    {% endblock %}
    
    <div class="container">
        <h1 class="text-center letraGrande">{{ data.titulo }}</h1>
        
        <p class="letraGrisMediana">
            <b>Cliente:</b> {{current_user.nombre}} <br><br>
            <b>Productos a comprar</b>
        </p>

        <table class="table table-striped mt-4">
            <thead>
                <tr>
                    <th scope="col" class="letraPeque" style="text-align: center; color:#129e31 ">Foto</th>
                    <th scope="col" class="letraPeque" style="text-align: center; color:#129e31 ">Nombre Producto</th>
                    <th scope="col" class="letraPeque" style="text-align: center; color:#129e31 ">Descripción Producto</th>
                    <th scope="col" class="letraPeque" style="text-align: center; color:#129e31 ">Cantidad</th>
                    <th scope="col" class="letraPeque" style="text-align: center; color:#129e31 ">Precio</th>
                </tr>
            </thead>
            <tbody>
                {% if data.cart_items %}
                    {% for key, item in data.cart_items.items() %}
                        <tr>
                            <td  style="text-align: center;"><img src="{{ url_for('static', filename='imagenes_productos/' + item['image']) }}" width="100px"></td>
                            <td class="letraGrisMediana" style="text-align: center;">{{ item['name'] }}</td>
                            <td class="letraGrisMediana" style="text-align: center;">{{ item['description'] }}</td>
                            <td class="letraGrisMediana" style="text-align: center;">{{ item['quantity']|int }}</td>
                            <td class="letraGrisMediana" style="text-align: center;">{{ '%.2f' % data.total_price|float }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="4" style="text-align: center;">Tu Carrito esta Vacio!.</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>

        <div class="row">
            <div class="col-md-6">
                <p class="font-weight-bold letraGrisMediana" style="font-size: 20px;">Total Productos: {{ data.total_quantity|int }}</p>
                <p class="font-weight-bold letraGrisMediana" style="font-size: 20px;">Total A pagar: ${{ '%.2f' % data.total_price|float }}</p>
            </div>
            <div class="col-md-6 mt-2">
                <form method="POST" action="{{ url_for('carrito.checkout') }}" id="payment-form">
                    <div id="card-element" class="form-group">
                        <!-- A Stripe Element will be inserted here. -->

                    </div>
                    <!-- Utiliza este campo para almacenar el token de pago -->
                    <input type="hidden" name="stripeToken" id="stripeToken">
                    <br>
                    <button type="submit" class="btn botonCuatro mt-4" id="submit-button">Finalizar Compra</button>
                </form>
            </div>
        </div>
    </div>
    <script>
        var stripe = Stripe('pk_test_51OKAeUJeE04wtf7VdSYu53wm4SrjuRMkmuWR8w36TAHcN7pGDYEMZB4LymqDznjzpKyWQXu6qvzo6t6tdy9XX4cZ00qJF9pgBB');
        var elements = stripe.elements();
    
        var card = elements.create('card');
        card.mount('#card-element');
    
        var form = document.getElementById('payment-form');
    
        form.addEventListener('submit', function (event) {
            event.preventDefault();
    
            stripe.createToken(card).then(function (result) {
                if (result.error) {
                    // Manejar errores de creación de token
                    console.error(result.error.message);
                } else {
                    // Adjuntar el token a la forma y enviarla
                    document.getElementById('stripeToken').value = result.token.id;
                    form.submit();
                }
            });
        });
    </script>
    
{% endblock %}