application/gatos/__init__.py
from flask import Blueprint

gatos = Blueprint('gatos', __name__, template_folder='templates')

from . import routes

application/gatos/routes.py
import math
from datetime import datetime
from flask import render_template, current_app, request
from application import db

from . import gatos

PRODUCTOS_POR_PAGINA = 6
fecha_actual = datetime.now()

def obtener_productos_gatos(page):
    """ obtener los productos relacionados con gatos"""
    try:
        with db.connection.cursor() as cur:
            consulta_sql = "SELECT * FROM producto WHERE fk_category = %s" 
            cur.execute(consulta_sql, (2,))
            productos = cur.fetchall()
            current_app.logger.info(f"{fecha_actual} Consulta SQL ejecutada: {consulta_sql}")
        
        orden = request.args.get('orden', 'nombre_asc')

        if orden == 'nombre_asc':
            productos = sorted(productos, key=lambda x: x[2])  # nombre ascendente
        elif orden == 'nombre_desc':
            productos = sorted(productos, key=lambda x: x[2], reverse=True)  # nombre descendente
        elif orden == 'precio_asc':
            productos = sorted(productos, key=lambda x: x[5])  # precio ascendente
        elif orden == 'precio_desc':
            productos = sorted(productos, key=lambda x: x[5], reverse=True)  # precio descendente
        
        elementos_por_pagina = PRODUCTOS_POR_PAGINA
        total_productos = len(productos)
        total_paginas = int(math.ceil(total_productos / elementos_por_pagina))
        inicio = (page - 1) * elementos_por_pagina
        fin = inicio + elementos_por_pagina
        productos_paginados = productos[inicio:fin]
        return {
            "productos": productos_paginados,
            "total_paginas": total_paginas,
            "pagina_actual": page,
            "elementos_por_pagina": elementos_por_pagina,
            "total_productos": total_productos,
            "orden": orden 
        }
    except Exception as e:
        current_app.logger.error(f"{fecha_actual} Error al obtener productos de gatos: {str(e)}")
        return None

@gatos.route("/gatos")
def gatos_productos():
    """Función para mostrar los productos de gatos"""
    data = {
        "titulo": "Gatos",
    }
    page = request.args.get('page', 1, type=int)
    productos_paginados = obtener_productos_gatos(page)
    if productos_paginados is not None:
        return render_template("gatos/gatos.html", data=data, productos=productos_paginados)
    else:
        return render_template("error/error.html", mensaje="Error al obtener productos de gatos")
    

application/gatos/templates/gatos/gatos.html
{% extends './base_template.html' %}

{% block title %}
{{ data.titulo }}
{% endblock %}

{% block body %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/productos.css') }}">

<div id="carouselExampleCaptions" class="carousel slide carousel-fade mt-2" data-bs-ride="carousel"
   data-bs-interval="5000" data-bs-pause="hover">
   <div class="carousel-indicators ">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
         aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
         aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
         aria-label="Slide 3"></button>
   </div>
   <div class="carousel-inner">
      <div class="carousel-item active">
         <img src="{{ url_for('static', filename='img/gato1.png') }}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
         <img src="{{ url_for('static', filename='img/gato2.png') }}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
         <img src="{{ url_for('static', filename='img/gato3.png') }}" class="d-block w-100" alt="...">
      </div>
   </div>
   <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
   </button>
   <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
   </button>
</div>

<div class="container">
   <h1 class="text-center my-5 letraExtraGrande">Nuestros Productos</h1>

   <div class="row">
      <div class="col-md-6 text-right">
         <form method="GET" action="{{ url_for('gatos.gatos_productos') }}">
            <label for="orden" class="letraGrisNormal form-label">Ordenar por:</label>
            <select name="orden" id="orden" onchange="this.form.submit()" class="form-select letraGrisNormal">
               <option value="nombre_asc" {% if productos['orden']=='nombre_asc' %}selected{% endif %}>
                  Nombre del producto (A-Z)
               </option>
               <option value="nombre_desc" {% if productos['orden']=='nombre_desc' %}selected{% endif %}>
                  Nombre del producto (Z-A)
               </option>
               <option value="precio_asc" {% if productos['orden']=='precio_asc' %}selected{% endif %}>
                  Precio: de menor a mayor
               </option>
               <option value="precio_desc" {% if productos['orden']=='precio_desc' %}selected{% endif %}>
                  Precio: de mayor a menor
               </option>
            </select>
         </form>
      </div>
   </div>

   {% if productos %}
   <div class="row mt-4">
      {% for producto in productos.productos %}
            <div class="col-md-4 mb-4">
                <div class="card h-100 border-0">
                  <img src="{{ url_for('static', filename='imagenes_productos/' + producto[3]) }}" class="card-img-top imagenProducto" alt="Producto Imagen">
                    <div class="card-body d-flex flex-column">
                        <div class="product-info">
                            <h5 class="card-title letraNormalVerde">{{ producto[2] }}</h5>
                            <p class="card-text letraGrisNormal mt-2">{{ producto[6] }}</p>
                        </div>
                        <div class="add-to-cart mt-3">
                            <form method="post" action="/cart" class="d-flex justify-content-between align-items-center">
                                <div class="form-group">
                                    <label for="" class="mr-3">Precio:</label>
                                    <h4 class="price letraPrecio">$ {{ producto[5] }}</h4>
                                </div>
                        
                                <div class="form-group">
                                    <label for="" class="mr-3">Cantidad:</label>
                                    <input type="number" class="product-quantity form-control" min="1" name="quantity" value="1" size="2" required/>
                                </div>
                        
                                <input type="hidden" name="code" value="{{ producto[1] }}" />
                                <input type="hidden" name="next" value="{{ request.url }}" />
                                <input type="submit" value="Añadir al Carrito" class="btn botonTres" />
                            </form>
                        </div>
                        
                    </div>
                </div>
            </div>
      {% endfor %}

   </div>
   <div class="pagination mt-4 text-center">
      {% if productos['pagina_actual'] > 1 %}
      <a href="{{ url_for('gatos.gatos_productos', page=productos['pagina_actual']-1, orden=productos['orden'])}}"
         class="btn letraMini">«
         Anterior</a>
      {% endif %}

      {% for num_pagina in range(1, productos['total_paginas']+1) %}
      {% if num_pagina == productos['pagina_actual'] %}
      <span class="current btn seleccionado">{{ num_pagina }}</span>
      {% else %}
      <a href="{{ url_for('gatos.gatos_productos', page=num_pagina, orden=productos['orden']) }}"
         class="btn botonPag">{{ num_pagina }}</a>
      {% endif %}
      {% endfor %}

      {% if productos['pagina_actual'] < productos['total_paginas'] %} <a
         href="{{ url_for('gatos.gatos_productos', page=productos['pagina_actual']+1, orden=productos['orden']) }}"
         class="btn letraMini">
         Siguiente »</a>
         {% endif %}
      <span class="current btn letraMini">Total registros {{ productos.total_productos }}</span>
   </div>
   {% else %}
   <p>No hay productos disponibles en esta categoría.</p>
   {% endif %}
</div>

{% endblock %}